
services:
  kestra:
    image: kestra/kestra:latest
    user: "root"
    command: server local
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ./kestra-creds.json:/root/kestra-creds.json:ro
      - ./application.yml:/app/application.yml:ro
    env_file:
      - .env_encoded
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/kestra-creds.json
      - KAGGLE_DATASET="devinanzelmo/dota-2-matches"
      - GCS_BUCKET="dota-project-raw-data"
      - GCS_PREFIX="raw/kaggle"