version: "3.8"

services:
  kestra:
    image: kestra/kestra:latest
    user: "root"
    command: server local
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ${HOME}/.config/gcloud:/root/.config/gcloud
      - ./application.yml:/app/application.yml:ro
    env_file:
      - .env_encoded
    environment:
      - KAGGLE_DATASET="devinanzelmo/dota-2-matches"
      - GCS_BUCKET="dota-project-raw-data"
      - GCS_PREFIX="raw/kaggle"